steps:
- uses: actions/checkout@v4
- name: Publish articles on dev.to
  uses: sinedied/publish-devto@v2
  with:
    devto_key: ${{ secrets.DEVTO_TOKEN }}
    files: 'blog/**/*.md'
    branch: main 
    conventional_commits: true
    dry_run: false
